name: aborigin-beautifulsoup
channels:
  - defaults
dependencies:
  - python=3.12.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - expat=2.6.4
  - libffi=3.4.4
  - openssl=3.0.16
  - pip=25.0
  - setuptools=75.8.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2025a
  - vc=14.42
  - vs2015_runtime=14.42.34433
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - attrs==25.3.0
      - beautifulsoup4==4.13.3
      - blinker==1.6.3
      - brotli==1.1.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - cryptography==44.0.3
      - h11==0.14.0
      - h2==4.2.0
      - hpack==4.1.0
      - hyperframe==6.1.0
      - idna==3.10
      - kaitaistruct==0.10
      - mutagen==1.47.0
      - outcome==1.3.0.post0
      - packaging==25.0
      - pyasn1==0.6.1
      - pycparser==2.22
      - pydivert==2.1.0
      - pydub==0.25.1
      - pyopenssl==25.0.0
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.0
      - requests==2.32.3
      - selenium==4.31.0
      - selenium-wire==5.1.0
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - trio==0.29.0
      - trio-websocket==0.12.2
      - typing-extensions==4.13.1
      - urllib3==2.3.0
      - webdriver-manager==4.0.2
      - websocket-client==1.8.0
      - wsproto==1.2.0
      - zstandard==0.23.0
